// Code generated by Wire protocol buffer compiler, do not edit.
// Source: LogPreferences in ls_message.proto
package me.pglvee.generation.protobuf

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic
import okio.ByteString

public class LogPreferences(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#UINT64",
    label = WireField.Label.OMIT_IDENTITY
  )
  public val id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "me.pglvee.generation.protobuf.LogPreferences${'$'}Type#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  public val type: Type = Type.UNKNOWN,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  public val token: String = "",
  @field:WireField(
    tag = 4,
    adapter = "me.pglvee.generation.protobuf.LogPreferences${'$'}UserInfo#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "userInfo"
  )
  public val user_info: UserInfo? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<LogPreferences, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN
  )
  public override fun newBuilder(): Nothing = throw AssertionError()

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LogPreferences) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (type != other.type) return false
    if (token != other.token) return false
    if (user_info != other.user_info) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + token.hashCode()
      result = result * 37 + user_info.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """type=$type"""
    result += """token=${sanitize(token)}"""
    if (user_info != null) result += """user_info=$user_info"""
    return result.joinToString(prefix = "LogPreferences{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Long = this.id,
    type: Type = this.type,
    token: String = this.token,
    user_info: UserInfo? = this.user_info,
    unknownFields: ByteString = this.unknownFields
  ): LogPreferences = LogPreferences(id, type, token, user_info, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LogPreferences> = object : ProtoAdapter<LogPreferences>(
      FieldEncoding.LENGTH_DELIMITED, 
      LogPreferences::class, 
      "type.googleapis.com/LogPreferences", 
      PROTO_3, 
      null
    ) {
      public override fun encodedSize(value: LogPreferences): Int {
        var size = value.unknownFields.size
        if (value.id != 0L) size += ProtoAdapter.UINT64.encodedSizeWithTag(1, value.id)
        if (value.type != Type.UNKNOWN) size += Type.ADAPTER.encodedSizeWithTag(2, value.type)
        if (value.token != "") size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.token)
        if (value.user_info != null) size += UserInfo.ADAPTER.encodedSizeWithTag(4, value.user_info)
        return size
      }

      public override fun encode(writer: ProtoWriter, value: LogPreferences): Unit {
        if (value.id != 0L) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.id)
        if (value.type != Type.UNKNOWN) Type.ADAPTER.encodeWithTag(writer, 2, value.type)
        if (value.token != "") ProtoAdapter.STRING.encodeWithTag(writer, 3, value.token)
        if (value.user_info != null) UserInfo.ADAPTER.encodeWithTag(writer, 4, value.user_info)
        writer.writeBytes(value.unknownFields)
      }

      public override fun decode(reader: ProtoReader): LogPreferences {
        var id: Long = 0L
        var type: Type = Type.UNKNOWN
        var token: String = ""
        var user_info: UserInfo? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.UINT64.decode(reader)
            2 -> try {
              type = Type.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> token = ProtoAdapter.STRING.decode(reader)
            4 -> user_info = UserInfo.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LogPreferences(
          id = id,
          type = type,
          token = token,
          user_info = user_info,
          unknownFields = unknownFields
        )
      }

      public override fun redact(value: LogPreferences): LogPreferences = value.copy(
        user_info = value.user_info?.let(UserInfo.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  public enum class Type(
    public override val value: Int
  ) : WireEnum {
    UNKNOWN(0),
    PC(1),
    MOBILE(2),
    WEB(3),
    ;

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<Type> = object : EnumAdapter<Type>(
        Type::class, 
        PROTO_3, 
        Type.UNKNOWN
      ) {
        public override fun fromValue(value: Int): Type? = Type.fromValue(value)
      }

      @JvmStatic
      public fun fromValue(value: Int): Type? = when (value) {
        0 -> UNKNOWN
        1 -> PC
        2 -> MOBILE
        3 -> WEB
        else -> null
      }
    }
  }

  public class UserInfo(
    @field:WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BYTES",
      label = WireField.Label.OMIT_IDENTITY
    )
    public val name: ByteString = ByteString.EMPTY,
    @field:WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY
    )
    public val avatar: String = "",
    @field:WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#UINT32",
      label = WireField.Label.OMIT_IDENTITY
    )
    public val age: Int = 0,
    unknownFields: ByteString = ByteString.EMPTY
  ) : Message<UserInfo, Nothing>(ADAPTER, unknownFields) {
    @Deprecated(
      message = "Shouldn't be used in Kotlin",
      level = DeprecationLevel.HIDDEN
    )
    public override fun newBuilder(): Nothing = throw AssertionError()

    public override fun equals(other: Any?): Boolean {
      if (other === this) return true
      if (other !is UserInfo) return false
      if (unknownFields != other.unknownFields) return false
      if (name != other.name) return false
      if (avatar != other.avatar) return false
      if (age != other.age) return false
      return true
    }

    public override fun hashCode(): Int {
      var result = super.hashCode
      if (result == 0) {
        result = unknownFields.hashCode()
        result = result * 37 + name.hashCode()
        result = result * 37 + avatar.hashCode()
        result = result * 37 + age.hashCode()
        super.hashCode = result
      }
      return result
    }

    public override fun toString(): String {
      val result = mutableListOf<String>()
      result += """name=$name"""
      result += """avatar=${sanitize(avatar)}"""
      result += """age=$age"""
      return result.joinToString(prefix = "UserInfo{", separator = ", ", postfix = "}")
    }

    public fun copy(
      name: ByteString = this.name,
      avatar: String = this.avatar,
      age: Int = this.age,
      unknownFields: ByteString = this.unknownFields
    ): UserInfo = UserInfo(name, avatar, age, unknownFields)

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<UserInfo> = object : ProtoAdapter<UserInfo>(
        FieldEncoding.LENGTH_DELIMITED, 
        UserInfo::class, 
        "type.googleapis.com/LogPreferences.UserInfo", 
        PROTO_3, 
        null
      ) {
        public override fun encodedSize(value: UserInfo): Int {
          var size = value.unknownFields.size
          if (value.name != ByteString.EMPTY) size += ProtoAdapter.BYTES.encodedSizeWithTag(1,
              value.name)
          if (value.avatar != "") size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.avatar)
          if (value.age != 0) size += ProtoAdapter.UINT32.encodedSizeWithTag(3, value.age)
          return size
        }

        public override fun encode(writer: ProtoWriter, value: UserInfo): Unit {
          if (value.name != ByteString.EMPTY) ProtoAdapter.BYTES.encodeWithTag(writer, 1,
              value.name)
          if (value.avatar != "") ProtoAdapter.STRING.encodeWithTag(writer, 2, value.avatar)
          if (value.age != 0) ProtoAdapter.UINT32.encodeWithTag(writer, 3, value.age)
          writer.writeBytes(value.unknownFields)
        }

        public override fun decode(reader: ProtoReader): UserInfo {
          var name: ByteString = ByteString.EMPTY
          var avatar: String = ""
          var age: Int = 0
          val unknownFields = reader.forEachTag { tag ->
            when (tag) {
              1 -> name = ProtoAdapter.BYTES.decode(reader)
              2 -> avatar = ProtoAdapter.STRING.decode(reader)
              3 -> age = ProtoAdapter.UINT32.decode(reader)
              else -> reader.readUnknownField(tag)
            }
          }
          return UserInfo(
            name = name,
            avatar = avatar,
            age = age,
            unknownFields = unknownFields
          )
        }

        public override fun redact(value: UserInfo): UserInfo = value.copy(
          unknownFields = ByteString.EMPTY
        )
      }

      private const val serialVersionUID: Long = 0L
    }
  }
}
